version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:2.5 # Ganti dengan versi yang benar
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    networks:
      - debezium-network

  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka:2.5 # Ganti dengan versi yang benar
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - debezium-network

  mysql:
    container_name: mysql
    image: quay.io/debezium/example-mysql:2.5 # Ganti dengan versi yang benar
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - debezium-network

  postgres:
    container_name: postgres
    image: quay.io/debezium/example-postgres:2.5 # Ganti dengan versi yang benar
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - debezium-network

  connect:
    container_name: connect
    image: quay.io/debezium/connect:2.5 # Ganti dengan versi yang benar
    ports:
      - '8083:8083'
    depends_on:
      - kafka
      - mysql
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - debezium-network

networks:
  debezium-network:
    driver: bridge
